# Generated by Django 4.2.5 on 2023-10-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codigoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emision', models.DateField(blank=True, null=True)),
                ('alta', models.DateField(blank=True, null=True)),
                ('nroFactura', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('oc', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('ff', models.CharField(blank=True, max_length=255, null=True)),
                ('unidadEjecutora', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto', models.CharField(blank=True, max_length=255, null=True)),
                ('fondoAfectado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.codigofinanciero')),
            ],
        ),
    ]
