# Generated by Django 4.2.5 on 2023-10-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.codigofinanciero', to_field='codigo'),
        ),
    ]
