# Generated by Django 4.2.5 on 2023-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_factura_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigofinanciero',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
