# Generated by Django 4.2.5 on 2023-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_codigofinanciero_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigofinanciero',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
